### ISSUE TITLE
Paper?

### ISSUE THREAD

**Issue by AbdullahSarhan** [rajasrijan/GlaucomaDetector#1]
Is there any paper that describes your approach?

**Comment by rajasrijan** [comment]
Please refer https://www.academia.edu/35315442/A_Project_Report_On_Biomedical_Imaging_for_Eye_Care

**Comment by AbdullahSarhan** [comment]
Hello Srijan,

Is it possible to get the mask you used for your images? I am trying to run
your application by just providing it a  fundus image but it requires also
the mask image. I would like to test it using your generated mask.

Thanks

**Comment by AbdullahSarhan** [comment]
Hello Srijan,

May you also provide which function in your code is responsible for
glaucoma classification. I am just able to see the find optic disk method
and its dependencies.

Thanks,
Abed
